version: "3.9"
services:
  kiwi:
    build:
      context: "../kiwi"
      dockerfile: Dockerfile
    # 80 container 8080 host.
    ports:
      - "8080:80"
    depends_on:
      - apteryx
  apteryx:
    build:
      context: .
      dockerfile: Dockerfile
    # 5000 container 5001 host.
    ports:
      - "5001:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    restart: always


